version: '3.8'
services:
  db:
    container_name: nesthw-db
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - greelow
  test-db:
    container_name: nesthw-test-db
    image: postgres:latest
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - greelow
networks:
  greelow:
